[build]
  ignore = "git log -1 --pretty=%B | grep dependabot"

[context.deploy-preview]
  command = "pnpm run build && rm -f build/mockServiceWorker.js && cp custom-headers/_preview_headers  build/_headers"
