
version: 2.1 # using 2.1 provides access to orbs and other features

jobs:

  install:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm ci
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - run:
          name: Upload coverage to codecov
          command: |
            curl -Os https://uploader.codecov.io/alpine/v0.1.0_6843 
            chmod +x codecov
            ./codecov -v
      - run:
          name: Upload coverage to codecov staging
          command: bash <(curl -s https://stage-web.codecov.dev/bash) -t $CODECOV_TOKEN_STAGING
      - run:
          name: Run eslint
          command: npm run lint

  sentry:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Sentry Release
          command: npm run sentry

  build:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Build the spa
          command: npm run build

  storybook:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy to Chromatic
          command: npm run chromatic

workflows:
  version: 2
  test-and-build:
    jobs:
      - install
      - storybook:
          filters:
            branches:
              ignore: /^dependabot.*/
          requires:
            - install
      - test:
          requires:
            - install
      - sentry:
          requires:
            - install
      # Disabling because we are no longer monitoring bundlesize
      # leaving the job to re enable this when I find a
      # replacement.
      # - build:
      #     requires:
      #       - install
