
version: 2.1 # using 2.1 provides access to orbs and other features

jobs:

  test:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn
      - run:
          name: Run tests
          command: yarn test:ci
      - run:
          name: Upload coverage to codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Upload coverage to codecov staging
          command: bash <(curl -s https://stage-web.codecov.dev/bash) -t $CODECOV_TOKEN_STAGING
      - run:
          name: Run eslint
          command: yarn lint

  build:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn
      - run:
          name: Build the spa
          command: yarn build
      - run:
          name: Check bundlesize
          command: yarn bundlesize

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
