name: Update Release

on:
  workflow_dispatch: {}

jobs:
  push_to_registry:
    name: Update PR for Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check branch
        run: |
          echo ${GITHUB_REF#refs/heads/} | grep release
          if [ $? -ne 0 ]; then
            echo "Invalid branch chosen"
            exit 1;
          fi

      - name: Build Enterprise
        env:
          ENV: enterprise
          NPM_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |-
          make build.enterprise

      - name: Dive
        env:
          ENV: production
        run: |-
          make dive

      - name: Deep Dive
        run: |-
          make deep-dive

      - name: Publish Enterprise
        env:
          ENV: enterprise
        run: |-
          make push.enterprise
